# Generated by Django 4.2.10 on 2025-04-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'uncompleted'), (1, 'completed'), (2, 'expired')], default=0)),
            ],
            options={
                'ordering': ['-deadline'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'uncompleted'), (1, 'completed'), (2, 'expired')], default=0)),
            ],
            options={
                'ordering': ['-deadline'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='grouptaskrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grouptaskrelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouptaskrelation',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='usertaskrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertaskrelation',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertaskrelation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergrouprelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usergrouprelation',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group'),
        ),
        migrations.DeleteModel(
            name='GroupTaskRelation',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTaskRelation',
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.group'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['deadline'], name='api_usertas_deadlin_920b35_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptask',
            index=models.Index(fields=['deadline'], name='api_groupta_deadlin_183822_idx'),
        ),
    ]
