# Generated by Django 4.2.10 on 2025-04-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptask',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['deadline']},
        ),
    ]
