# Generated by Django 5.1.7 on 2025-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
