# Generated by Django 5.1.7 on 2025-04-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_last_seen_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
